### ISSUE TITLE
Entity Parameter

### ISSUE THREAD

**Issue by mathieu-ducrot** [smartbooster/parameter-bundle#2]
## Todos

- [x] Configuration
- [x] Entity
- [x] ParameterProvider
- [x] ParameterLoader
- [x] Command
- [x] Sonata Admin

### Configuration

```yaml
smart_parameter:
  parameters:
    dummy_parameter:
      value:
      help:
    another_dummy_parameter:
      value:
      help:
```

Test the configuration with a AppKernel class specified in phpunit.xml.dist

### ParameterProvider

Cache the parameter on first call to encrease performance

### ParameterLoader

- Insert all not existing param in database from the configuration
- Update help attribut for existing param
- Remove parameter from db not matching configuration code

### Sonata Admin

- Remove create route
- Disable Help Edit
